version: '3.1'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3200:3000
    volumes:
      - ./img/:/usr/share/grafana/public/img
      - ./grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - ./config.env
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  prom2teams:
    image: idealista/prom2teams
    environment:
      - PROM2TEAMS_CONNECTOR=https://vingroupjsc.webhook.office.com/webhookb2/608e7d88-953e-4b92-993a-4868e12e9f9c@ed6a2939-d153-4f92-94f8-3d790d96c9f8/IncomingWebhook/aea56a1ef7764fe08d19ad8e54f73ea8/d00189c6-110a-4646-b08a-d17483facab3
    ports:
      - 8089:8089
    restart: always