# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 10.124.69.101:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/etc/prometheus/network_rule.yml'
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # - job_name: 'kafka'
  #   # metrics_path defaults to '/metrics'
  #   # scheme defaults to 'http'.
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['10.124.69.101:7075', '10.124.64.127:7075', '10.124.64.120:7075']

  # - job_name: 'system'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['10.124.64.120:9100', '10.124.69.101:9100', '10.124.64.127:9100']

  # - job_name: 'minio-job'
  #   metrics_path: '/minio/v2/metrics/cluster'
  #   scrape_interval: 5s
  #   scheme: 'http'
  #   static_configs:
  #     - targets: ['10.124.69.121:9000']

  - job_name: 'dcgm-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.124.64.125:9400']
      
  - job_name: 'nvidia-gpu'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.124.64.125:9835']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.124.64.125:9100']
